### ISSUE TITLE
Suggestion: option to not use standardization

### ISSUE THREAD

**Issue by folivetti** [EpistasisLab/regression-benchmark#18]
I've noticed that you're standardizing the predictors and target variable before fitting the regression models:

https://github.com/EpistasisLab/regression-benchmark/blob/967c66beec7e79ef53d6a3bb133190887224cfc1/experiment/evaluate_model.py#L47-L49

In my experience my algorithm works best without any normalization. I also tested a few datasets with KernelRidge with and without standardization and it seems to also work better without this transformation. Maybe add an option to use the standardized data set or not.

**Comment by lacava** [comment]
sounds reasonable. i'm working on adding a configurable option now.

**Comment by lacava** [comment]
you can now specify eval_kwargs = {'scale_x': False, 'scale_y': False} in the method file to set this. For KernelRidge [scaling X is important](https://sebastianraschka.com/Articles/2014_about_feature_scaling.html), but we could probably turn it off for `y` and for tree methods. 

closing now, but feel free to open back up if needed.
